'use strict';

/* ============================================================
   NAV — active link on scroll
   ============================================================ */
const navLinks = document.querySelectorAll('.nav a');
const sectionIds = ['unit1', 'unit2', 'unit3', 'unit4', 'unit5', 'unit6', 'mcq'];

function updateActiveNavLink() {
  let current = sectionIds[0];
  for (const id of sectionIds) {
    const el = document.getElementById(id);
    if (el && window.scrollY >= el.offsetTop - 80) current = id;
  }
  navLinks.forEach(a => {
    a.classList.toggle('active', a.getAttribute('href') === '#' + current);
  });
}
window.addEventListener('scroll', updateActiveNavLink);

/* ============================================================
   MCQ QUIZ ENGINE
   Loads a local, pre-generated question bank (questions.json,
   built by generate_questions.py) instead of calling a live API
   from the browser — that never worked without a server-side key.
   ============================================================ */
const Quiz = (() => {
  const TOTAL_FOR_PROGRESS = 20; // progress bar treats a 20-question run as "full"

  let allQuestions = [];         // full bank loaded from questions.json
  let pool = [];                 // remaining, not-yet-asked questions for current filter
  let currentUnit = 'all';       // 'all' or '1'..'6'
  let currentQuestion = null;
  let answered = false;
  let scoreCorrect = 0;
  let scoreTotal = 0;
  let questionCount = 0;

  const els = {};

  function cacheEls() {
    els.quizContent = document.getElementById('quiz-content');
    els.progress = document.getElementById('progress');
    els.nextBtn = document.getElementById('next-btn');
    els.scoreCorrect = document.getElementById('score-correct');
    els.scoreTotal = document.getElementById('score-total');
  }

  function shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }

  function rebuildPool() {
    const source = currentUnit === 'all'
      ? allQuestions
      : allQuestions.filter(q => String(q.unit) === String(currentUnit));
    pool = shuffle(source);
  }

  function loadBank() {
    // QUESTION_BANK comes from questions.js (loaded via a plain <script> tag
    // in index.html, generated by generate_questions.py). We deliberately do
    // NOT fetch() a .json file here: browsers block fetch() of local files
    // under file://, so anyone who opens index.html by double-clicking it
    // would see the quiz fail to load. A <script>-tag global works everywhere.
    if (typeof QUESTION_BANK === 'undefined' || !Array.isArray(QUESTION_BANK) || QUESTION_BANK.length === 0) {
      throw new Error('Question bank not found — make sure questions.js is loaded before script.js.');
    }
    allQuestions = QUESTION_BANK;
  }

  function setUnit(unit) {
    currentUnit = unit;
    document.querySelectorAll('.fbtn').forEach(b => {
      b.classList.toggle('on', b.dataset.unit === unit);
    });
    rebuildPool();
  }

  function pickNextQuestion(randomizeUnit) {
    if (randomizeUnit) {
      const units = ['1', '2', '3', '4', '5', '6'];
      const unit = units[Math.floor(Math.random() * units.length)];
      setUnit(unit);
    }

    if (pool.length === 0) rebuildPool();      // ran out — reshuffle and continue
    if (pool.length === 0) return null;        // bank truly empty for this filter

    return pool.pop();
  }

  function renderLoading(unitLabel) {
    els.quizContent.innerHTML = `
      <div class="loading-state"><span class="loader"></span> Loading question${unitLabel ? ' — ' + unitLabel : ''}...</div>`;
  }

  function renderError(message) {
    els.quizContent.innerHTML = `
      <div class="error-state">Could not load a question.<br><small>${escapeHtml(message)}</small></div>
      <button class="btn btn-gold" style="margin-top:1rem" onclick="Quiz.next()">Retry</button>`;
  }

  function escapeHtml(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }

  function renderQuestion(q) {
    const letters = ['A', 'B', 'C', 'D'];
    const optsHtml = q.options.map((opt, i) => `
      <button class="opt" id="opt${i}" onclick="Quiz.answer(${i})">
        <span class="opt-letter">${letters[i]}</span>
        <span class="opt-text">${escapeHtml(opt)}</span>
      </button>`).join('');

    els.quizContent.innerHTML = `
      <div class="q-card">
        <div class="q-meta">
          <span class="q-unit-badge">Unit ${q.unit}</span>
          <span>Q${questionCount}</span>
        </div>
        <div class="q-text">${escapeHtml(q.question)}</div>
        <div class="opts">${optsHtml}</div>
        <div class="explanation" id="explanation">
          <strong>&check; Explanation:</strong> ${escapeHtml(q.explanation)}
        </div>
      </div>`;
  }

  function next(randomizeUnit) {
    answered = false;
    els.nextBtn.style.display = 'none';

    const q = pickNextQuestion(!!randomizeUnit);
    if (!q) {
      renderError('No questions available for this filter yet.');
      return;
    }

    currentQuestion = q;
    questionCount++;
    const pct = Math.min((questionCount / TOTAL_FOR_PROGRESS) * 100, 100);
    els.progress.style.width = pct + '%';

    renderQuestion(q);
  }

  function answer(selectedIndex) {
    if (answered || !currentQuestion) return;
    answered = true;
    scoreTotal++;

    const correctIndex = currentQuestion.correct;
    document.querySelectorAll('.opt').forEach((btn, i) => {
      btn.disabled = true;
      if (i === correctIndex) btn.classList.add('correct');
      else if (i === selectedIndex) btn.classList.add('wrong');
    });

    if (selectedIndex === correctIndex) scoreCorrect++;
    els.scoreCorrect.textContent = scoreCorrect;
    els.scoreTotal.textContent = scoreTotal;

    const exp = document.getElementById('explanation');
    if (exp) exp.classList.add('show');
    els.nextBtn.style.display = 'inline-block';
  }

  function init() {
    cacheEls();
    renderLoading('');
    try {
      loadBank();
      rebuildPool();
      next(false);
    } catch (err) {
      renderError(err.message);
    }
  }

  return { init, next, answer, setUnit: (unit, btn) => setUnit(unit) };
})();

// Expose the handful of functions the inline HTML onclick attributes call.
function loadNewQuestion(random) { Quiz.next(!!random); }
function setUnit(unit, btn) { Quiz.setUnit(unit, btn); }
function answer(selected) { Quiz.answer(selected); }

document.addEventListener('DOMContentLoaded', () => {
  updateActiveNavLink();
  Quiz.init();
});
